# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Shibasis Patel
tagline:             'A CSE undergraduate'
description:         'A Second year Computer Science and Engineering Undergraduate in IIIT Bhubaneswar'
url:                 http://shibasisp.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shibasis Patel
  url:               https://twitter.com/smartshibasish
  email:             smartshibasish@gmail.com

# Custom vars
version:             1.0.0

#Gems
gems: [jekyll-paginate, jekyll-gist]

#navigation bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  

#Kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

